global: {}
mq-spring-app:
  replicaCount: 2
  configmap:
    CONNECTION_NAME: qm-dev-ibm-mq.staging.svc.cluster.local(1414)
post-sync-job:
  name: mq-spring-app-stage-to-prod-postsync-trigger
  argocdhook: PostSync
  serviceaccount: pipeline
  container:
    image: "registry.access.redhat.com/ubi8"
    imagePullPolicy: "Always"
    command: "curl"
    args:
      - "-X"
      - "POST"
      - "-H"
      - "Content-Type: application/json"
      - "--data"
      - "{}"
      - "http://mq-spring-app-post-stage-ci.itzroks-661002q71v-tkv3jb-4b4a324f027aea19c5cbc0c3275c4656-0000.us-east.containers.appdomain.cloud/"
