global: {}
mq-infra:
  replicaCount: 1
post-sync-job:
  name: mq-infra-stage-to-prod-postsync-trigger
  argocdhook: PostSync
  serviceaccount: pipeline
  container:
    image: registry.access.redhat.com/ubi8
    imagePullPolicy: Always
    command: "curl"
    args:
      - "-X"
      - "POST"
      - "-H"
      - "Content-Type: application/json"
      - "--data"
      - "{}"
      - "http://mq-infra-post-stage-ci.itzroks-661002q71v-tkv3jb-4b4a324f027aea19c5cbc0c3275c4656-0000.us-east.containers.appdomain.cloud"
